spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      static-path-pattern: /resources/**
  factory:
    anntotation:
      Autowired: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.poczta.onet.pl
    port: 587
    username: testowaniepoczty09876@onet.pl
    password: QazWsx0987!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
