spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      static-path-pattern: /resources/**
  factory:
    anntotation:
      Autowired: true
  main:
    allow-bean-definition-overriding: true