spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/websystems
    username: postgres
    # TODO: change password
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
    javax:
      persistence:
        schema-generation:
          create-database-schemas: true