spring:
  datasource:
    url: jdbc:h2:mem:web_system_db;INIT=CREATE SCHEMA IF NOT EXISTS "WEBSYSTEM"
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./src/main/resources/schema.sql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false